### PR TITLE
change default scope, restrict search to inbox, change server to api.protonmail.ch

### PR DESCRIPTION
**Pull request by bartbutler**
Not tested. Very soon 'mail' scope will be required to access mail, so setting the Scope parameter to "full mail" to ensure your users will still be able to use your extension. I also changed the API server to the long-term one--the protonmail.com/api one will probably be removed at some point.

P.S. I didn't see any logout code. Do you log the user out between checks or create a new session every time you check for mail? Can you fix this? Lots of dead tokens are really a problem but they aren't great either.

### CODE REVIEW

**Comment by JamesCullum** [comment]
Hey bart,

Thanks for the participation, really appreciate it!
I'll review your request later on and merge it accordingly.
Your long-term changes are already working, right?

Users dont get logged out as the session gets automatically destroyed when the popup gets closed. Is there a possibility to backup the data and set them again to be immediately logged in?
Especially - is there a more performant way for the hidden-login that the popup does in a frame?

**Comment by bartbutler** [comment]
Yes, URL and scope are ready now. If you backup the tokens you should be able to reuse them for the next call. Then you can eliminate saving the user's login credentials, which is much safer (they can be read from the auth requests in the dev console at the very least).

The access tokens currently last for 100 hours (might reduce this), but the refresh tokens last for 30 days (won't reduce this), so if you get a 401 status code for an API request you can use the refresh token to get a new access token. This is what we do in the web app--we have an interceptor which checks for status code 401, uses refresh token to get new access token, then retries the request.

The urgent change is the scope though...that restriction will be live in a few days.

**Comment by JamesCullum** [comment]
I dont see how i can offer users to not save their credentials. At least once they need to enter their credentials to even get their logged in tokens.

I'd appreciate you supporting me on terms of login, maybe you can write a small example on which tokens to set from where? Your pull request will be merged either ways.

**Comment by JamesCullum** [comment]
The API needs to be fixed, it is missing the Access-Control-Allow-Origin Header, see error below.

> XMLHttpRequest cannot load https://api.protonmail.ch/auth. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'chrome-extension://lblkcchjaapfgjpopdnjhojbhoiodfjh' is therefore not allowed access.

**Comment by bartbutler** [comment]
does mail.protonmail.com/api/auth work?

**Comment by JamesCullum** [comment]
Actually i went a little more into detail. It looks like the problem is coming from somewhere else. Your SSL certificate on api.protonmail.com is invalid: https://api.protonmail.com/, the API subdomain is not listed in the SAN. 

Therefore the browser (Chrome 49) rejects any connection. I'm sure you can replicate this easily using any modern browser. It looks like your infrastructur is not quite ready to use this subdomain.

**Comment by bartbutler** [comment]
That's not it. It's api.protonmail.ch, not .com. I know why this doesn't work, I'm just curious how it worked before, because the origin restrictions have been there forever.

**Comment by JamesCullum** [comment]
Oh youre right, confused that when checking in detail. I'll take another look on how to make it run.

**Comment by JamesCullum** [comment]
Found the cause of the error. To get past the CORS restrictions we need to add the domain to the manifest.js. I did try it with a protonmail.com wildcard but, as here again, forgot that its .ch. Its working now.

**Comment by bartbutler** [comment]
Nice.

**Pull request merged**
